SaveFile: nov.txt
BaseUrl: http://
ExUrl: book.zongheng.com/chapter/672340/36898237.html
PatternNextUrl: "<a href=\"http://(.*?)\".*>下一[页|章]</a>"
PatternTitle: '<div class=\"title_txtbox\">(.*?)</div>'
PatternContent: '<div class=\"content\" itemprop="acticleBody">([\s\S]*?)</div>'
encoding: utf-8
ctreplace: ['<p>','','</p>',\n]   #ctreplace[1]替换ctreplace[0];
headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
  Accept-Language: "zh-CN,zh;q=0.9"
  Accept-Encoding: "gzip, deflate"  
